// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXzlHU6D3MKtw1szdvtXbidQKkXDCNu8E',
    appId: '1:288563352164:web:ff40976fe4dea2a6284571',
    messagingSenderId: '288563352164',
    projectId: 'modesta-clean',
    authDomain: 'modesta-clean.firebaseapp.com',
    storageBucket: 'modesta-clean.firebasestorage.app',
    measurementId: 'G-WXPSDECBBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCARv_Ui9yACOZ5xFZtyIXFClG5d7b3DqA',
    appId: '1:288563352164:android:d6cb48357c02dd20284571',
    messagingSenderId: '288563352164',
    projectId: 'modesta-clean',
    storageBucket: 'modesta-clean.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBK5-cINuSfDNIfpci_Eo6TdS3gmJAal6s',
    appId: '1:288563352164:ios:26b41bf2d57cab95284571',
    messagingSenderId: '288563352164',
    projectId: 'modesta-clean',
    storageBucket: 'modesta-clean.firebasestorage.app',
    iosClientId: '288563352164-hbq7cekm9ntif950b598u1uktr8duj50.apps.googleusercontent.com',
    iosBundleId: 'com.example.modestaClean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBK5-cINuSfDNIfpci_Eo6TdS3gmJAal6s',
    appId: '1:288563352164:ios:26b41bf2d57cab95284571',
    messagingSenderId: '288563352164',
    projectId: 'modesta-clean',
    storageBucket: 'modesta-clean.firebasestorage.app',
    iosClientId: '288563352164-hbq7cekm9ntif950b598u1uktr8duj50.apps.googleusercontent.com',
    iosBundleId: 'com.example.modestaClean',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXzlHU6D3MKtw1szdvtXbidQKkXDCNu8E',
    appId: '1:288563352164:web:04b7e2de813e3e8b284571',
    messagingSenderId: '288563352164',
    projectId: 'modesta-clean',
    authDomain: 'modesta-clean.firebaseapp.com',
    storageBucket: 'modesta-clean.firebasestorage.app',
    measurementId: 'G-MPCZ2XV1KV',
  );

}